Test/361 select
ScottLogic/lookingatyou pull request #367
Opened 2019-07-31 08:50 UTC by alicolver

Issue #361. Writing select tests.

2019-07-31 16:03 UTC, w-reilly requested changes
Generally happy, but just being mean and requesting changes as unit tests are often overlooked and would like to encourage good practice here too

2019-08-01 11:08 UTC, connor-settle requested changes

2019-08-01 15:40 UTC, connor-settle approved these changes

2019-08-02 10:12 UTC, w-reilly approved these changes

2019-08-02 10:13 UTC, merged